name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

permissions: {} # Each job defines its own permissions explicitly

jobs:
  build:
    name: Build
    permissions:
      contents: read # Access to check out code and install dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v7

      - name: Set up pnpm package manager
        uses: pnpm/setup@v2
        with:
          cache: true

      - name: Install dependencies
        run: pnpm install

      - name: Check code formatting with Oxfmt
        run: pnpm run format:check

      - name: Lint code with Oxlint
        run: pnpm run lint

      - name: Build
        run: pnpm run build
